### PR TITLE
remove anvio

### PR DESCRIPTION
**Pull request by ozcan**
Hi, 
This formula installs a really old version and not maintained. Can we remove it?

### CODE REVIEW

**Comment by dpo** [comment]
This tap isn't maintained. We normally remove a formula from here when an updated version is available elsewhere.

@sjackman Would `anvio` be appropriate for brewsci/homebrew-bio?

**Comment by ozcan** [comment]
Thanks for the reply @dpo. I was maintaining this formula for a long time, but we started using conda instead as our userbase demanded it. 
This formula has many (20+) pypi dependencies and we do release somewhat frequently. Keeping all the pypi links and hashes updated requires some manual work, so I found conda better suits for our use case, just listing pypi dependencies. So I am not going to maintain

**Comment by sjackman** [comment]
Hi, Özcan. I've created a new formula for `anvio` here:
https://github.com/brewsci/homebrew-bio/pull/559/files
You'll see that it should be a lot easier to maintain than the previous one.

It works fine locally, but on CircleCI and Azure I'm getting this odd error:
```
==> pip3 install --prefix=/home/linuxbrew/.linuxbrew/Cellar/anvio/5.3/libexec .
Processing /tmp/anvio-20190219-19644-vchggv/anvio-5.3
Files/directories not found in /tmp/pip-req-build-qah_lkc6/pip-egg-info
```

I'm not quite sure what the error means or what's causing it. I'll troubleshoot it later this week.

**Comment by sjackman** [comment]
Merged. Thanks for the PR, Özcan.

**Pull request merged**
